### ISSUE TITLE
Typos in README.md

### ISSUE THREAD

**Issue by Mamboleoo** [DeNepo/welcome-to-js#11]
Hey,
As I was reading the documentation, I listed the little typos I found.
I can open a PR if you want :)

1. I think there is a word (or more) missing in the following sentence:
`"that you could with enough time"`
https://github.com/HackYourFutureBelgium/welcome-to-js/blob/627e5161aca787f65a030eaa32c0864a4ad75759/README.md?plain=1#L46-L48
2. [...] is *its* value
https://github.com/HackYourFutureBelgium/welcome-to-js/blob/627e5161aca787f65a030eaa32c0864a4ad75759/README.md?plain=1#L141
3. [...] change *its* behavior 
https://github.com/HackYourFutureBelgium/welcome-to-js/blob/627e5161aca787f65a030eaa32c0864a4ad75759/README.md?plain=1#L204-L205
4. Checkbox missing for those two steps
https://github.com/HackYourFutureBelgium/welcome-to-js/blob/627e5161aca787f65a030eaa32c0864a4ad75759/README.md?plain=1#L211
https://github.com/HackYourFutureBelgium/welcome-to-js/blob/627e5161aca787f65a030eaa32c0864a4ad75759/README.md?plain=1#L218
5. Install *or* update
https://github.com/HackYourFutureBelgium/welcome-to-js/blob/627e5161aca787f65a030eaa32c0864a4ad75759/README.md?plain=1#L244
6. *Windows (capital)
https://github.com/HackYourFutureBelgium/welcome-to-js/blob/627e5161aca787f65a030eaa32c0864a4ad75759/README.md?plain=1#L268

**Comment by colevandersWands** [comment]
Thanks for spotting these!  PRs are great, otherwise I can take care of it later today.

**Comment by Mamboleoo** [comment]
Pull request opened :)
