### ISSUE TITLE
Missing step at: 3-understanding-programs

### ISSUE THREAD

**Issue by kostasx** [DeNepo/welcome-to-js#31]
Should there be a step 5 in [https://github.com/DeNepo/welcome-to-js/tree/main/3-understanding-programs](https://github.com/DeNepo/welcome-to-js/tree/main/3-understanding-programs)?

**Comment by colevandersWands** [comment]
Looks like a mistake.  I checked some notes and the commit history, it looks like i just messed up at the ["reordering" commit](https://github.com/DeNepo/welcome-to-js/commits/main/3-understanding-programs).  

I'll push the right order later today
