### ISSUE TITLE
puzzlecode domain is dead

### ISSUE THREAD

**Issue by colevandersWands** [DeNepo/welcome-to-js#33]
The domain puzzlecode.org in `/developing-programs/pair-programming` is no longer the right place.  

- [ ] set up an alternate hosting of https://github.com/mikegagnon/puzzlecode

**Comment by kostasx** [comment]
Replaced PuzzleCode with [Exercism](https://github.com/in-tech-gration/welcome-to-js/blob/main/4-developing-programs/0-pair-programming/README.md), until we find a way to make PuzzleCode accessible again.

That's the whole idea of school-in-a-box. Integrate as much as we can, so we don't run into these problems in the future.

**Comment by kostasx** [comment]
PuzzleCode has been integrated into WDX-180. [Live link](https://in-tech-gration.github.io/WDX-180/resources/javascript/puzzlecode/).

Updated [README](https://github.com/in-tech-gration/welcome-to-js/blob/main/4-developing-programs/0-pair-programming/README.md).

Next task, integrated the [wiki](https://github.com/mikegagnon/puzzlecode/wiki/Goto-instruction)

**Comment by colevandersWands** [comment]
@kostasx, I switched to small JS programs instead.  

- keep everything local
- the programs are from previous exercises so they shouldn't be too hard
- practice pair programming in context

Puzzlecode is still great, I'll think on where it could be.  maybe a stand-alone exercise one day?
