### ISSUE TITLE
Missing link: session-agenda.md

### ISSUE THREAD

**Issue by kostasx** [DeNepo/welcome-to-js#34]
https://github.com/DeNepo/welcome-to-js/blob/73fd18d207cbbb2cfa57d7212eabd51137ba2944/3-understanding-programs/2-reading-programs/README.md?plain=1#L35

Where exactly should this link point to?

**Comment by colevandersWands** [comment]
It's supposed to link here.  I must have moved from a single file to a folder and missed this link:
- https://github.com/DeNepo/welcome-to-js/tree/main/3-understanding-programs/2-reading-programs/code-reading-sessions
