### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by kostasx** [DeNepo/welcome-to-js#35]
https://github.com/DeNepo/welcome-to-js/blob/73fd18d207cbbb2cfa57d7212eabd51137ba2944/3-understanding-programs/2-reading-programs/code-reading-sessions/README.md?plain=1#L10

- https://runner.code-reading.org-
- https://annotate.code-reading.org

**Comment by colevandersWands** [comment]
Looks like they've moved here:
- https://codereading.club/resources
